import numpy as np
Tracker_params = {
                    "input_shape": (144, 144, 3),
                    "use_densenet_backend": True,
                    "densenet_name": 'DenseNet121',
                    "num_of_blocks": 3,
                    "alpha": 1.5,
                    "regularization_epsilon": 0.0001,
                    "std_moving_average": 1,
                    "write_rect_json": False,
                    "use_combine_only_in_segmentation": False,
                    "num_of_ldas_color": 1,
                    "num_of_ldas": [4, 4, 1, 1],
                    "exp_scale_factor": 4,
                    "f1_alpha": 1,
                    "small_mask_ratio": 0.00048,
                    "allowed_mask_ratio": 1.5,
                    "thresh_initial_color": 0.8,
                    "f1_total_thresh": 0.1,
                    "save_images": True,
                    "is_debug_mode": True,
                    "plot_lda_related": False,
                    "debug_images_path": 'D:/Felix/TrackDebugs/',
                    "base_vot_path": "D:/Felix/Aharon Bar Hillel Repo/Sandboxes/Felix/vot-toolkit-master/vot-workspace/sequences/",
                    "track_results_path": 'D:/Felix/TrackResults/',
                    "base_vos_path": 'D:/Felix/DAVIS Stuff/DAVIS',
                    "vos_results_path": 'D:/Felix/DAVIS Stuff/DAVIS/Results/Segmentations/480p/Davis_Results/'
                  }

Segmentation_params = dict(power_gradient_score=10,
                           alpha_grad=3.5,
                           grad_score_coeff=2,
                           displacement_score_coeff=1,
                           volume_score_coeff=0.5,
                           thresholds=np.arange(0.3, 0.8, 0.05),
                           anchor_threshold_range=[0.3, 0.8],
                           min_area_mult=0.01,
                           max_area_mult=100,
                           enable_grad=1,
                           enable_confidence=1,
                           enable_volume=1,
                           enable_displacement=1)